In [ ]:
#Manupulating data
#deleting multiple elements
import pandas as pd

In [ ]:
sales = pd.Series(
    [5000, 7000, None, 9000, 8000, 10000, None],
    index=[
        'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'
    ]
)

print(sales)
#aggregation
sales['Tuesday']=9500
print(sales)
sales['Jan']=7800
print(sales)

Monday        5000.0
Tuesday       7000.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
dtype: float64
Monday        5000.0
Tuesday       9500.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
dtype: float64
Monday        5000.0
Tuesday       9500.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
Jan           7800.0
dtype: float64

In [ ]:
print(sales.min())

5000.0

In [ ]:
print(sales.max())

10000.0

In [ ]:
print(sales.mean())

7800.0

In [ ]:
print(sales.sum())

39000.0

In [ ]:
print(sales.var())

3700000.0

In [ ]:
print(sales.std())

1923.5384061671346

In [ ]:
print(sales.dtype) #check the data type

float64

In [ ]:
print(sales+2000)

Monday        7000.0
Tuesday      11500.0
Wednesday        NaN
Thursday     11000.0
Friday       10000.0
Saturday     12000.0
Sunday           NaN
Jan           9800.0
dtype: float64

In [ ]:
print(sales*2)

Monday       10000.0
Tuesday      19000.0
Wednesday        NaN
Thursday     18000.0
Friday       16000.0
Saturday     20000.0
Sunday           NaN
Jan          15600.0
dtype: float64

In [ ]:
#combine two series
s=pd.Series([1,2,3,4,5]) #index=[9,7,6,8,9])
s1=pd.Series([101,102,103,104,105]) #index=[901,902,903,904,905])
print(s)
print(s1)
d=pd.concat([s,s1])
c=pd.concat([s,s1],ignore_index=True)
print(c)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    101
1    102
2    103
3    104
4    105
dtype: int64
0      1
1      2
2      3
3      4
4      5
5    101
6    102
7    103
8    104
9    105
dtype: int64

In [ ]:
data = {
    'Name': ['Mahesh','Ram','Harika','Harini','Shankar','Sravani','Deekshith','Chanikhya'],
    'Age': [27,21,19,20,21,30,10,15],
    'City': ['Hyderabad','Vizag','Vizag','Hyd','Vizag','Hyderabad','Bangalore','Chennai'],
    'Salary': [20000,30000,40000,45000,50000,30000,35000,25000]}

df =pd.DataFrame(data,index=[101,102,103,104,105,106,107,108])
print(df)

          Name  Age       City  Salary
101     Mahesh   27  Hyderabad   20000
102        Ram   21      Vizag   30000
103     Harika   19      Vizag   40000
104     Harini   20        Hyd   45000
105    Shankar   21      Vizag   50000
106    Sravani   30  Hyderabad   30000
107  Deekshith   10  Bangalore   35000
108  Chanikhya   15    Chennai   25000

In [ ]:
print(df['Age'].sum())
print(df['Age'].max())
print(df['Age'].min())
print(df['Age'].mean())
print(df['Age'].var())
print(df['Age'].std())

163
30
10
20.375
39.410714285714285
6.2777953363991

In [ ]:
print(df['Salary'].sum())
print(df['Salary'].max())
print(df['Salary'].min())
print(df['Salary'].mean())
print(df['Salary'].var())
print(df['Salary'].std())

275000
50000
20000
34375.0
103125000.0
10155.04800579495

In [ ]:
df['Bonus']=df['Salary']*0.10
print(df)

          Name  Age       City  Salary   Bonus
101     Mahesh   27  Hyderabad   20000  2000.0
102        Ram   21      Vizag   30000  3000.0
103     Harika   19      Vizag   40000  4000.0
104     Harini   20        Hyd   45000  4500.0
105    Shankar   21      Vizag   50000  5000.0
106    Sravani   30  Hyderabad   30000  3000.0
107  Deekshith   10  Bangalore   35000  3500.0
108  Chanikhya   15    Chennai   25000  2500.0

In [ ]:
df['new_salary']=df['Salary']+df['Bonus']
print(df)

          Name  Age       City  Salary   Bonus  new_salary
101     Mahesh   27  Hyderabad   20000  2000.0     22000.0
102        Ram   21      Vizag   30000  3000.0     33000.0
103     Harika   19      Vizag   40000  4000.0     44000.0
104     Harini   20        Hyd   45000  4500.0     49500.0
105    Shankar   21      Vizag   50000  5000.0     55000.0
106    Sravani   30  Hyderabad   30000  3000.0     33000.0
107  Deekshith   10  Bangalore   35000  3500.0     38500.0
108  Chanikhya   15    Chennai   25000  2500.0     27500.0

In [ ]:
df['Age']=df['Age']+1
print(df)

          Name  Age       City  Salary   Bonus  new_salary
101     Mahesh   28  Hyderabad   20000  2000.0     22000.0
102        Ram   22      Vizag   30000  3000.0     33000.0
103     Harika   20      Vizag   40000  4000.0     44000.0
104     Harini   21        Hyd   45000  4500.0     49500.0
105    Shankar   22      Vizag   50000  5000.0     55000.0
106    Sravani   31  Hyderabad   30000  3000.0     33000.0
107  Deekshith   11  Bangalore   35000  3500.0     38500.0
108  Chanikhya   16    Chennai   25000  2500.0     27500.0

In [ ]:
df['new_salary']=df['new_salary']+500
print(df)

          Name  Age       City  Salary   Bonus  new_salary
101     Mahesh   28  Hyderabad   20000  2000.0     22500.0
102        Ram   22      Vizag   30000  3000.0     33500.0
103     Harika   20      Vizag   40000  4000.0     44500.0
104     Harini   21        Hyd   45000  4500.0     50000.0
105    Shankar   22      Vizag   50000  5000.0     55500.0
106    Sravani   31  Hyderabad   30000  3000.0     33500.0
107  Deekshith   11  Bangalore   35000  3500.0     39000.0
108  Chanikhya   16    Chennai   25000  2500.0     28000.0

In [ ]:
df.loc[df['Name'] =='Ram','City'] = 'Hyderabad'
print(df)

          Name  Age       City  Salary   Bonus  new_salary
101     Mahesh   28  Hyderabad   20000  2000.0     22500.0
102        Ram   22  Hyderabad   30000  3000.0     33500.0
103     Harika   20      Vizag   40000  4000.0     44500.0
104     Harini   21        Hyd   45000  4500.0     50000.0
105    Shankar   22      Vizag   50000  5000.0     55500.0
106    Sravani   31  Hyderabad   30000  3000.0     33500.0
107  Deekshith   11  Bangalore   35000  3500.0     39000.0
108  Chanikhya   16    Chennai   25000  2500.0     28000.0

In [ ]:
df.loc[df['City'] == 'Bangalore','City'] = 'Hyderabad'
print(df)

          Name  Age       City  Salary   Bonus  new_salary
101     Mahesh   28  Hyderabad   20000  2000.0     22500.0
102        Ram   22  Hyderabad   30000  3000.0     33500.0
103     Harika   20      Vizag   40000  4000.0     44500.0
104     Harini   21        Hyd   45000  4500.0     50000.0
105    Shankar   22      Vizag   50000  5000.0     55500.0
106    Sravani   31  Hyderabad   30000  3000.0     33500.0
107  Deekshith   11  Hyderabad   35000  3500.0     39000.0
108  Chanikhya   16    Chennai   25000  2500.0     28000.0

In [ ]:
df.loc[df['City']=='Hyderabad','Salary']=df["Salary"]*1.05
print(df)

          Name  Age       City     Salary   Bonus  new_salary
101     Mahesh   28  Hyderabad  23152.500  2000.0     22500.0
102        Ram   22  Hyderabad  34728.750  3000.0     33500.0
103     Harika   20      Vizag  40000.000  4000.0     44500.0
104     Harini   21        Hyd  45000.000  4500.0     50000.0
105    Shankar   22      Vizag  50000.000  5000.0     55500.0
106    Sravani   31  Hyderabad  34728.750  3000.0     33500.0
107  Deekshith   11  Hyderabad  40516.875  3500.0     39000.0
108  Chanikhya   16    Chennai  25000.000  2500.0     28000.0

In [ ]:
df.loc[df['Salary']<=45000,'Salary']=60000
print(df)

          Name  Age       City   Salary   Bonus  new_salary
101     Mahesh   28  Hyderabad  60000.0  2000.0     22500.0
102        Ram   22  Hyderabad  60000.0  3000.0     33500.0
103     Harika   20      Vizag  60000.0  4000.0     44500.0
104     Harini   21        Hyd  60000.0  4500.0     50000.0
105    Shankar   22      Vizag  50000.0  5000.0     55500.0
106    Sravani   31  Hyderabad  60000.0  3000.0     33500.0
107  Deekshith   11  Hyderabad  60000.0  3500.0     39000.0
108  Chanikhya   16    Chennai  60000.0  2500.0     28000.0

In [ ]:
df.drop('Bonus',axis=1,inplace=True)
print(df)

          Name  Age       City   Salary  new_salary
101     Mahesh   28  Hyderabad  60000.0     22500.0
102        Ram   22  Hyderabad  60000.0     33500.0
103     Harika   20      Vizag  60000.0     44500.0
104     Harini   21        Hyd  60000.0     50000.0
105    Shankar   22      Vizag  50000.0     55500.0
106    Sravani   31  Hyderabad  60000.0     33500.0
107  Deekshith   11  Hyderabad  60000.0     39000.0
108  Chanikhya   16    Chennai  60000.0     28000.0

In [ ]:
df.drop(columns='new_salary',inplace=True)
print(df)

          Name  Age       City   Salary
101     Mahesh   28  Hyderabad  60000.0
102        Ram   22  Hyderabad  60000.0
103     Harika   20      Vizag  60000.0
104     Harini   21        Hyd  60000.0
105    Shankar   22      Vizag  50000.0
106    Sravani   31  Hyderabad  60000.0
107  Deekshith   11  Hyderabad  60000.0
108  Chanikhya   16    Chennai  60000.0

Day - 06

In [ ]:
import pandas as pd
employees = {
    "EmpID": [101,102,103,104],
    "Name": ["Ram",None,"Harika","Sai"],
    "Department": ["Sales","IT","HR",None],
    "Salary": [45000,60000,None,89000]
}
I = [901,902,903,904]
df = pd.DataFrame(employees,index = I)
print(df)
df.groupby('Department')['Salary'].mean()

     EmpID    Name Department   Salary
901    101     Ram      Sales  45000.0
902    102    None         IT  60000.0
903    103  Harika         HR      NaN
904    104     Sai       None  89000.0

Department
HR           NaN
IT       60000.0
Sales    45000.0
Name: Salary, dtype: float64

In [ ]:
df.groupby('Department')['Salary'].max()

Department
HR           NaN
IT       60000.0
Sales    45000.0
Name: Salary, dtype: float64

In [ ]:
df.groupby('Department')['Salary'].min()

Department
HR           NaN
IT       60000.0
Sales    45000.0
Name: Salary, dtype: float64

In [ ]:
df.groupby('Department')['Salary'].std()

Department
HR      NaN
IT      NaN
Sales   NaN
Name: Salary, dtype: float64

In [ ]:
df.groupby('Department')['Salary'].agg(['mean','max','min'])

               mean      max      min
Department
HR              NaN      NaN      NaN
IT          60000.0  60000.0  60000.0
Sales       45000.0  45000.0  45000.0

In [ ]:
data = {
    'Name': ['Mahesh','Ram','Harika','Harini','Shankar','Sravani','Deekshith','Chanikhya'],
    'Age': [27,21,19,20,21,30,10,15],
    'City': ['Hyderabad','Vizag','Vizag','Hyd','Vizag','Hyderabad','Bangalore','Chennai'],
    'Salary': [20000,30000,40000,45000,50000,30000,35000,25000]}

df =pd.DataFrame(data,index=[101,102,103,104,105,106,107,108])
print(df)

          Name  Age       City  Salary
101     Mahesh   27  Hyderabad   20000
102        Ram   21      Vizag   30000
103     Harika   19      Vizag   40000
104     Harini   20        Hyd   45000
105    Shankar   21      Vizag   50000
106    Sravani   30  Hyderabad   30000
107  Deekshith   10  Bangalore   35000
108  Chanikhya   15    Chennai   25000

In [ ]:
print(df['Name'])

101       Mahesh
102          Ram
103       Harika
104       Harini
105      Shankar
106      Sravani
107    Deekshith
108    Chanikhya
Name: Name, dtype: object

In [ ]:
print(df[['Name','Salary']])

          Name  Salary
101     Mahesh   20000
102        Ram   30000
103     Harika   40000
104     Harini   45000
105    Shankar   50000
106    Sravani   30000
107  Deekshith   35000
108  Chanikhya   25000

In [ ]:
print(df['Age']>23)

101     True
102    False
103    False
104    False
105    False
106     True
107    False
108    False
Name: Age, dtype: bool

In [ ]:
print(df['Salary']>40000)

101    False
102    False
103    False
104     True
105     True
106    False
107    False
108    False
Name: Salary, dtype: bool

In [ ]:
df[df['City']=='Chennai']

          Name  Age     City  Salary
108  Chanikhya   15  Chennai   25000

In [ ]:
df[(df['Age']>22) & (df['Salary']>20000)]

        Name  Age       City  Salary
106  Sravani   30  Hyderabad   30000

In [ ]:
df[(df['City'] == 'Mumbai') | (df['City'] == 'Bangalore')]

          Name  Age       City  Salary
107  Deekshith   10  Bangalore   35000

In [ ]:
df[['Name','Salary']][df['Salary']>30000]

          Name  Salary
103     Harika   40000
104     Harini   45000
105    Shankar   50000
107  Deekshith   35000

In [ ]:
df.iloc[1:4]

       Name  Age   City  Salary
102     Ram   21  Vizag   30000
103  Harika   19  Vizag   40000
104  Harini   20    Hyd   45000

Day - 07

Handling Duplicates

In [ ]:
import pandas as pd
data = {
    "EmpID":[101,102,103,104,105,106,107,108,109,110,110],

    "Name":["Ravi","PRIYA","Arun","sneha","Kiran","ANJALI","Vikram","meena","RAHUL","Sneha","Sneha"],

    "City":["Hyderabad","hyderabad","CHENNAI","Chennai","Bangalore","BANGALORE","Mumbai","mumbai","Delhi","Hyderabad","Hyderabad"],

    "Salary":[30000,40000,35000,45000,32000,50000,38000,42000,36000,45000,45000]

}

df=pd.DataFrame(data)

print(df)

    EmpID    Name       City  Salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  hyderabad   40000
2     103    Arun    CHENNAI   35000
3     104   sneha    Chennai   45000
4     105   Kiran  Bangalore   32000
5     106  ANJALI  BANGALORE   50000
6     107  Vikram     Mumbai   38000
7     108   meena     mumbai   42000
8     109   RAHUL      Delhi   36000
9     110   Sneha  Hyderabad   45000
10    110   Sneha  Hyderabad   45000

In [ ]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
dtype: bool

In [ ]:
df[df.duplicated()]

    EmpID   Name       City  Salary
10    110  Sneha  Hyderabad   45000

In [ ]:
df[df.duplicated()]

    EmpID   Name       City  Salary
10    110  Sneha  Hyderabad   45000

In [ ]:
df.duplicated().sum()

np.int64(1)

In [ ]:
d=df[df.duplicated()]
total = d[["Name"]].sum()
print(total)

Name    Sneha
dtype: object

In [ ]:
duplicate_rows = df[df.duplicated(keep=False)]
print(duplicate_rows)

    EmpID   Name       City  Salary
9     110  Sneha  Hyderabad   45000
10    110  Sneha  Hyderabad   45000

In [ ]:
df["EmpID"].duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
Name: EmpID, dtype: bool

In [ ]:
d=df[df.duplicated()]
total = d[["Name"]].sum()
duplicate_rows = df[df.duplicated(keep=False)]
print(duplicate_rows)
f=df["EmpID"].duplicated()
print(f)

    EmpID   Name       City  Salary
9     110  Sneha  Hyderabad   45000
10    110  Sneha  Hyderabad   45000
0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
Name: EmpID, dtype: bool

In [ ]:
df.drop_duplicates()

   EmpID    Name       City  Salary
0    101    Ravi  Hyderabad   30000
1    102   PRIYA  hyderabad   40000
2    103    Arun    CHENNAI   35000
3    104   sneha    Chennai   45000
4    105   Kiran  Bangalore   32000
5    106  ANJALI  BANGALORE   50000
6    107  Vikram     Mumbai   38000
7    108   meena     mumbai   42000
8    109   RAHUL      Delhi   36000
9    110   Sneha  Hyderabad   45000

In [ ]:
df.drop_duplicates(keep="last")

    EmpID    Name       City  Salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  hyderabad   40000
2     103    Arun    CHENNAI   35000
3     104   sneha    Chennai   45000
4     105   Kiran  Bangalore   32000
5     106  ANJALI  BANGALORE   50000
6     107  Vikram     Mumbai   38000
7     108   meena     mumbai   42000
8     109   RAHUL      Delhi   36000
10    110   Sneha  Hyderabad   45000

In [ ]:
df.drop_duplicates(keep="first")

   EmpID    Name       City  Salary
0    101    Ravi  Hyderabad   30000
1    102   PRIYA  hyderabad   40000
2    103    Arun    CHENNAI   35000
3    104   sneha    Chennai   45000
4    105   Kiran  Bangalore   32000
5    106  ANJALI  BANGALORE   50000
6    107  Vikram     Mumbai   38000
7    108   meena     mumbai   42000
8    109   RAHUL      Delhi   36000
9    110   Sneha  Hyderabad   45000

In [ ]:
df.drop_duplicates(keep=False)

   EmpID    Name       City  Salary
0    101    Ravi  Hyderabad   30000
1    102   PRIYA  hyderabad   40000
2    103    Arun    CHENNAI   35000
3    104   sneha    Chennai   45000
4    105   Kiran  Bangalore   32000
5    106  ANJALI  BANGALORE   50000
6    107  Vikram     Mumbai   38000
7    108   meena     mumbai   42000
8    109   RAHUL      Delhi   36000

In [ ]:
duplicate_all = df[df.duplicated(keep=False)]
display(duplicate_all)

    EmpID   Name       City  Salary
9     110  Sneha  Hyderabad   45000
10    110  Sneha  Hyderabad   45000

In [ ]:
df.duplicated().sum()

np.int64(1)

In [ ]:
df[df.duplicated(keep=False)]

    EmpID   Name       City  Salary
9     110  Sneha  Hyderabad   45000
10    110  Sneha  Hyderabad   45000

In [ ]:
amount=df[df.duplicated()]
print(amount["Salary"])

10    45000
Name: Salary, dtype: int64

Day - 08

In [38]:
data = {

   "VisitID": [501, 502, 503, 504, 505,

               506, 507, 508, 509, 510, 510, 511],

   "Patient": ["Rahul", "Anita", "Suresh", "Priya", "Kiran",

               "Anjali", "Ravi", "Meena", "Arun", "Priya",

               "Priya", "Kiran"],

   "Department": ["Cardiology", "Neurology", "Orthopedic", "General",

                  "Dental", "Cardiology", "Neurology", "General",

                  "Dental", "Cardiology", "Cardiology", "Dental"],

   "BillAmount": [5000, 7500, 4500, 2000, 1500,

                  6000, 7000, 2500, 1800, 6000,6000, 1500]}

df = pd.DataFrame(data)

print(df)

    VisitID Patient  Department  BillAmount
0       501   Rahul  Cardiology        5000
1       502   Anita   Neurology        7500
2       503  Suresh  Orthopedic        4500
3       504   Priya     General        2000
4       505   Kiran      Dental        1500
5       506  Anjali  Cardiology        6000
6       507    Ravi   Neurology        7000
7       508   Meena     General        2500
8       509    Arun      Dental        1800
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
11      511   Kiran      Dental        1500

In [43]:
df.duplicated().sum()

np.int64(0)

In [42]:
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [VisitID, Patient, Department, BillAmount]
Index: []

In [30]:
dup=df[df.duplicated()]
print(dup['BillAmount'])

10    6000
Name: BillAmount, dtype: int64

In [31]:
df[df['VisitID'].duplicated()]

    VisitID Patient  Department  BillAmount
10      510   Priya  Cardiology        6000

In [32]:
df[df['Patient'].duplicated(keep=False)]

    VisitID Patient  Department  BillAmount
3       504   Priya     General        2000
4       505   Kiran      Dental        1500
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
11      511   Kiran      Dental        1500

In [44]:
df.drop_duplicates()

    VisitID Patient  Department  BillAmount
0     501.0   Rahul  Cardiology        5000
1     502.0   Anita   Neurology        7500
2     503.0  Suresh  Orthopedic        4500
3     504.0   Priya     General        2000
4     505.0   Kiran      Dental        1500
5     506.0  Anjali  Cardiology        6000
6     507.0    Ravi   Neurology        7000
7     508.0   Meena     General        2500
8     509.0    Arun      Dental        1800
9     510.0   Priya  Cardiology        6000
10      NaN   Priya  Cardiology        6000
11    511.0   Kiran      Dental        1500

In [46]:
df['VisitID']=df['VisitID'].drop_duplicates()

In [47]:
print(df)

    VisitID Patient  Department  BillAmount
0     501.0   Rahul  Cardiology        5000
1     502.0   Anita   Neurology        7500
2     503.0  Suresh  Orthopedic        4500
3     504.0   Priya     General        2000
4     505.0   Kiran      Dental        1500
5     506.0  Anjali  Cardiology        6000
6     507.0    Ravi   Neurology        7000
7     508.0   Meena     General        2500
8     509.0    Arun      Dental        1800
9     510.0   Priya  Cardiology        6000
10      NaN   Priya  Cardiology        6000
11    511.0   Kiran      Dental        1500

In [48]:
df[['Patient','Department']].drop_duplicates(keep="first")

  Patient  Department
0   Rahul  Cardiology
1   Anita   Neurology
2  Suresh  Orthopedic
3   Priya     General
4   Kiran      Dental
5  Anjali  Cardiology
6    Ravi   Neurology
7   Meena     General
8    Arun      Dental
9   Priya  Cardiology

In [49]:
print(df)

    VisitID Patient  Department  BillAmount
0     501.0   Rahul  Cardiology        5000
1     502.0   Anita   Neurology        7500
2     503.0  Suresh  Orthopedic        4500
3     504.0   Priya     General        2000
4     505.0   Kiran      Dental        1500
5     506.0  Anjali  Cardiology        6000
6     507.0    Ravi   Neurology        7000
7     508.0   Meena     General        2500
8     509.0    Arun      Dental        1800
9     510.0   Priya  Cardiology        6000
10      NaN   Priya  Cardiology        6000
11    511.0   Kiran      Dental        1500